version: "3.8"

services:

  rust:
    container_name: "hypixel_auctions"
    build:
      context: .
    networks:
      - default
      - cassandraNet

  cassandra:
    container_name: "auctions_db"
    image: cassandra:4.1
    volumes:
      - cassandradb:/var/lib/cassandra/data
    networks:
      - cassandraNet
    ports:
      - "9042:9042"

volumes:
  cassandradb:

networks:
  cassandraNet:
